name: 'Repository Restore'
description: 'Restores a backed-up GitHub repository using secure OTP and file ID through File Security API.'
author: 'your-github-username'

inputs:
  activation_code:
    description: 'Activation code for API'
    required: true
  encryption_key:
    description: 'Secret key for decrypting the backup'
    required: true
  restore_github_token:
    description: 'Token for repository mirror'
    required: true
  record_id:
    description: 'Enter RECORD_ID to retrieve a specific backup file.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get Activation Token
      id: get_token
      shell: bash
      run: |
        RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "https://dev.api.file-security.icredible.com/endpoint/activation" \
        -H "Content-Type: application/json" \
        -d '{
          "activationCode": "${{ inputs.activation_code }}",
          "uniqueId": "${{ github.repository_id }}",
          "ip": "${{ runner.ip }}",
          "operatingSystem": "Linux",
          "endpointType": "Workstation",
          "endpointName": "Github Endpoint (${{ github.repository }})"
        }')

        HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)
        JSON_BODY=$(echo "$RESPONSE" | head -n -1)

        if [ "$HTTP_STATUS" -ne 200 ]; then
          echo "Failed to get token" && exit 1
        fi

        TOKEN=$(echo "$JSON_BODY" | jq -r '.data.token')
        echo "TOKEN=$TOKEN" >> $GITHUB_ENV

    - name: Request OTP (With Debug Output)
      shell: bash
      run: |
        echo "Requesting OTP..."
        RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "https://dev.api.file-security.icredible.com/OTP/Send" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ env.TOKEN }}" \
          -d '{
            "Source": "FileDownload",
            "OtpGenerationMode": "Number",
            "Type": "MAIL"
          }')
    
        HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)
        JSON_BODY=$(echo "$RESPONSE" | head -n -1)
    
        echo "--- RAW API RESPONSE ---"
        echo "$RESPONSE"
        echo "-------------------------"
        echo "HTTP STATUS: $HTTP_STATUS"
        echo "JSON BODY: $JSON_BODY"
    
        if [ "$HTTP_STATUS" -ne 200 ]; then
          echo "OTP request failed. Status: $HTTP_STATUS"
          echo "Message: $(echo "$JSON_BODY" | jq -r '.message // .error // .msg // .description // "No error message provided"')"
          exit 1
        fi
    
        UNIQUE_KEY=$(echo "$JSON_BODY" | jq -r '.data.uniqueKey')
        echo "UNIQUE_KEY=$UNIQUE_KEY" >> $GITHUB_ENV


    - name: Await OTP Input
      id: await_otp
      uses: step-security/wait-for-secrets@v1
      with:
        secrets: |
          RESTORE_OTP_INPUT:
            name: 'Restore OTP'
            description: 'Enter OTP received via email'

    - name: Set OTP After Await
      shell: bash
      run: |
        echo "USER_OTP=${{ steps.await_otp.outputs.RESTORE_OTP_INPUT }}" >> $GITHUB_ENV

    - name: Retrieve Backup
      shell: bash
      run: |
        echo "Retrieving backup file..."
        RESPONSE=$(curl -s -w "\n%{http_code}" -X GET "https://dev.api.file-security.icredible.com/restore/${{ inputs.record_id }}" \
        -H "Authorization: Bearer ${{ env.TOKEN }}" \
        -H "X-Verification-Key: ${{ env.USER_OTP }}" \
        -H "X-Unique-Key: ${{ env.UNIQUE_KEY }}"  -o repo.tar.zst.enc)
        echo "Raw API Response: $RESPONSE"
        HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)
        JSON_BODY=$(echo "$RESPONSE" | head -n -1)
        if [ "$HTTP_STATUS" -ne 200 ]; then
          echo "Failed to obtain backup file. Response: $RESPONSE"
          echo "Error: Received HTTP status $HTTP_STATUS"
          echo "Response: $JSON_BODY"
          exit 1
        fi
        echo "Backup file retrieved successfully."

    - name: Decrypt and Extract Backup
      shell: bash
      run: |
        echo "Decryption repository"
        openssl enc -d -aes-256-cbc -pbkdf2 -in repo.tar.zst.enc -out repo.tar.zst -pass pass:${{ inputs.encryption_key }}
        echo "Extracting repository backup..."        
        zstd -d repo.tar.zst -o repo.tar
        mkdir repo-mirror repo-metadata
        tar -xf repo.tar -C .
        rm -f repo.tar repo.tar.zst
        echo "Decryption and extraction complete."

    - name: Git Configuration
      shell: bash
      run: |
        cd repo-mirror
        git config user.name "myapp File Security"
        git config user.email "file-security@myapp.com"
        git config url."https://x-access-token:${{ inputs.restore_github_token }}@github.com/".insteadOf https://github.com/

    - name: Install GitHub CLI
      shell: bash
      run: |
        # Install GH CLI without verbose output
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg 2>/dev/null
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list >/dev/null
        sudo apt-get update -qq
        sudo apt-get install -y gh jq -qq
        
    - name: Push Restored Repository
      shell: bash
      run: |
        cd repo-mirror
        git remote set-url origin https://x-access-token:${{ inputs.restore_github_token }}@github.com/${{ github.repository }}.git
        
        # Temporarily disable branch protections
        protected_branches=$(gh api -X GET "/repos/${{ github.repository }}/branches?protected=true" -q '.[].name' 2>/dev/null || echo "")
        for branch in $protected_branches; do
          gh api -X DELETE "/repos/${{ github.repository }}/branches/$branch/protection"
        done
        
        git push --mirror --force
        
        # Re-enable branch protections
        for branch in $protected_branches; do
          echo "Re-enabling protection for $branch"
          gh api -X PUT "/repos/${{ github.repository }}/branches/$branch/protection" \
            -f '{
              "required_status_checks": null,
              "enforce_admins": true,
              "required_pull_request_reviews": null,
              "restrictions": null
            }'
        done
        
        echo "Code repository restored successfully."
  

    - name: Restore Branches and Pull Requests
      shell: bash
      run: |
        # Tüm branch'leri geri yükle
        jq -c '.data.repository.refs.nodes[]' repo-metadata/branches.json | while read branch; do
          branch_name=$(echo "$branch" | jq -r '.name')
          commit_sha=$(echo "$branch" | jq -r '.target.oid')
          
          # Branch'i oluştur ve commit'e işaret et
          git checkout -b "$branch_name" "$commit_sha"
          git push origin "$branch_name"
        done

        # PR'ları orijinal durumlarına getir
        jq -c '.[]' repo-metadata/pull_requests.json | while read pr; do
          pr_state=$(echo "$pr" | jq -r '.state')
          pr_number=$(echo "$pr" | jq -r '.number')
          
          if [ "$pr_state" == "CLOSED" ]; then
            gh pr close "$pr_number"
          elif [ "$pr_state" == "MERGED" ]; then
            # PR'ı merge et (simüle etmek için)
            gh pr merge "$pr_number" --merge
          fi
        done
      env:
        GH_TOKEN: ${{ inputs.restore_github_token }}

    - name: Import Repository Metadata
      shell: bash
      run: |
        # Restore labels
        jq -c '.data.repository.labels.nodes[]' repo-metadata/labels_milestones.json | while read label; do
          name=$(jq -r '.name' <<< "$label")
          gh label create "$name" --color "$(jq -r '.color' <<< "$label")" --description "$(jq -r '.description // ""' <<< "$label")" || true
        done
        
        # Restore milestones
        jq -c '.data.repository.milestones.nodes[]' repo-metadata/labels_milestones.json | while read milestone; do
          title=$(jq -r '.title' <<< "$milestone")
          gh milestone create "$title" \
            --description "$(jq -r '.description // ""' <<< "$milestone")" \
            --due-date "$(jq -r '.dueOn // ""' <<< "$milestone")" || true
        done
        
        # Restore issues
        jq -c '.[]' repo-metadata/issues.json | while read issue; do
          body=$(jq -r '.body' <<< "$issue")
          gh issue create \
            --title "$(jq -r '.title' <<< "$issue")" \
            --body "$body" \
            --label "$(jq -r '.labels[].name' <<< "$issue" | tr '\n' ',' | sed 's/,$//')" || true
            
          if [ "$(jq -r '.state' <<< "$issue")" = "CLOSED" ]; then
            issue_number=$(gh issue list --json number,title -q ".[] | select(.title == \"$(jq -r '.title' <<< "$issue")\") | .number")
            gh issue close "$issue_number" || true
          fi
        done
        
        # Restore PRs as issues
        jq -c '.[]' repo-metadata/pull_requests.json | while read pr; do
          head_ref=$(jq -r '.headRefName' <<< "$pr")
          base_ref=$(jq -r '.baseRefName' <<< "$pr")
          pr_body=$(jq -r '.body' <<< "$pr")
          enhanced_body="## Restored Pull Request
          **From:** \`$head_ref\`  
          **To:** \`$base_ref\`  
          **Original State:** $(jq -r '.state' <<< "$pr")
          
          $pr_body"
          
          gh issue create \
            --title "[PR] #$(jq -r '.number' <<< "$pr"): $(jq -r '.title' <<< "$pr")" \
            --body "$enhanced_body" \
            --label "$(jq -r '.labels[].name' <<< "$pr" | tr '\n' ',' | sed 's/,$//')" || true
            
          if [ "$(jq -r '.state' <<< "$pr")" != "OPEN" ]; then
            issue_number=$(gh issue list --json number,title -q ".[] | select(.title | contains(\"$(jq -r '.title' <<< "$pr")\")) | .number")
            gh issue close "$issue_number" || true
          fi
        done

    
