name: 'Repository Restore'
description: 'Restores a backed-up GitHub repository using secure OTP and file ID through File Security API.'
author: 'your-github-username'

inputs:
  activation_code:
    description: 'Activation code for API'
    required: true
  encryption_key:
    description: 'Secret key for decrypting the backup'
    required: true
  restore_github_token:
    description: 'Token for repository mirror'
    required: true
  record_id:
    description: 'Enter RECORD_ID to retrieve a specific backup file.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get Activation Token
      id: get_token
      shell: bash
      run: |
        RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "https://dev.api.file-security.icredible.com/endpoint/activation" \
        -H "Content-Type: application/json" \
        -d '{
          "activationCode": "${{ inputs.activation_code }}",
          "uniqueId": "${{ github.repository_id }}",
          "ip": "${{ runner.ip }}",
          "operatingSystem": "Linux",
          "endpointType": "Workstation",
          "endpointName": "Github Endpoint (${{ github.repository }})"
        }')

        HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)
        JSON_BODY=$(echo "$RESPONSE" | head -n -1)

        if [ "$HTTP_STATUS" -ne 200 ]; then
          echo "Failed to get token" && exit 1
        fi

        TOKEN=$(echo "$JSON_BODY" | jq -r '.data.token')
        echo "TOKEN=$TOKEN" >> $GITHUB_ENV

    - name: Request OTP (With Debug Output)
      shell: bash
      run: |
        echo "Requesting OTP..."
        RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "https://dev.api.file-security.icredible.com/OTP/Send" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ env.TOKEN }}" \
          -d '{
            "Source": "FileDownload",
            "OtpGenerationMode": "Number",
            "Type": "MAIL"
          }')
    
        HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)
        JSON_BODY=$(echo "$RESPONSE" | head -n -1)
    
        echo "--- RAW API RESPONSE ---"
        echo "$RESPONSE"
        echo "-------------------------"
        echo "HTTP STATUS: $HTTP_STATUS"
        echo "JSON BODY: $JSON_BODY"
    
        if [ "$HTTP_STATUS" -ne 200 ]; then
          echo "OTP request failed. Status: $HTTP_STATUS"
          echo "Message: $(echo "$JSON_BODY" | jq -r '.message // .error // .msg // .description // "No error message provided"')"
          exit 1
        fi
    
        UNIQUE_KEY=$(echo "$JSON_BODY" | jq -r '.data.uniqueKey')
        echo "UNIQUE_KEY=$UNIQUE_KEY" >> $GITHUB_ENV


    - name: Await OTP Input
      id: await_otp
      uses: step-security/wait-for-secrets@v1
      with:
        secrets: |
          RESTORE_OTP_INPUT:
            name: 'Restore OTP'
            description: 'Enter OTP received via email'

    - name: Set OTP After Await
      shell: bash
      run: |
        echo "USER_OTP=${{ steps.await_otp.outputs.RESTORE_OTP_INPUT }}" >> $GITHUB_ENV

    - name: Retrieve Backup
      shell: bash
      run: |
        echo "Retrieving backup file..."
        RESPONSE=$(curl -s -w "\n%{http_code}" -X GET "https://dev.api.file-security.icredible.com/restore/${{ inputs.record_id }}" \
        -H "Authorization: Bearer ${{ env.TOKEN }}" \
        -H "X-Verification-Key: ${{ env.USER_OTP }}" \
        -H "X-Unique-Key: ${{ env.UNIQUE_KEY }}"  -o repo.tar.zst.enc)
        echo "Raw API Response: $RESPONSE"
        HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)
        JSON_BODY=$(echo "$RESPONSE" | head -n -1)
        if [ "$HTTP_STATUS" -ne 200 ]; then
          echo "Failed to obtain backup file. Response: $RESPONSE"
          echo "Error: Received HTTP status $HTTP_STATUS"
          echo "Response: $JSON_BODY"
          exit 1
        fi
        echo "Backup file retrieved successfully."

    - name: Decrypt and Extract Backup
      shell: bash
      run: |
        echo "Decryption repository"
        openssl enc -d -aes-256-cbc -pbkdf2 -in repo.tar.zst.enc -out repo.tar.zst -pass pass:${{ inputs.encryption_key }}
        echo "Extracting repository backup..."        
        zstd -d repo.tar.zst -o repo.tar
        mkdir repo-mirror repo-metadata
        tar -xf repo.tar -C .
        rm -f repo.tar repo.tar.zst
        echo "Decryption and extraction complete."

    - name: Git Configuration
      shell: bash
      run: |
        cd repo-mirror
        git config user.name "myapp File Security"
        git config user.email "file-security@myapp.com"
        git config url."https://x-access-token:${{ inputs.restore_github_token }}@github.com/".insteadOf https://github.com/

    - name: Push Restored Repository
      shell: bash
      run: |
        cd repo-mirror
        git remote set-url origin https://x-access-token:${{ inputs.restore_github_token }}@github.com/${{ github.repository }}.git
        git push --mirror
        echo "Code repository restored successfully."
    
    - name: Install GitHub CLI
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y gh

    - name: Import Repository Metadata
      shell: bash
      run: |
        # GH_TOKEN çakışmasını önle
        unset GH_TOKEN

        # Doğrudan token ile kimlik doğrulama
        echo "${{ inputs.restore_github_token }}" | gh auth login --with-token

        # Etiketleri içe aktar
        jq -c '.data.repository.labels.nodes[]' repo-metadata/labels_milestones.json | while read label; do
          name=$(echo "$label" | jq -r '.name')
          color=$(echo "$label" | jq -r '.color')
          desc=$(echo "$label" | jq -r '.description // ""')
          
          # Etiket zaten var mı kontrol et
          if ! gh label list | grep -q "$name"; then
            gh label create "$name" --color "$color" --description "$desc"
          else
            echo "Etiket '$name' zaten var, atlanıyor"
          fi
        done

        # Milestone'ları içe aktar
        jq -c '.data.repository.milestones.nodes[]' repo-metadata/labels_milestones.json | while read milestone; do
          title=$(echo "$milestone" | jq -r '.title')
          desc=$(echo "$milestone" | jq -r '.description // ""')
          due=$(echo "$milestone" | jq -r '.dueOn // ""')
          
          # Milestone zaten var mı kontrol et
          if ! gh milestone list | grep -q "$title"; then
            gh milestone create "$title" --description "$desc" $([ -n "$due" ] && echo "--due-date $due")
          else
            echo "Milestone '$title' zaten var, atlanıyor"
          fi
        done

        # Issue'ları içe aktar
        jq -c '.[]' repo-metadata/issues.json | while read issue; do
          body=$(echo "$issue" | jq -r '.body' | sed 's/\\n/\\\\n/g')
          gh issue create \
            --title "$(echo "$issue" | jq -r '.title')" \
            --body "$body" \
            $([ "$(echo "$issue" | jq -r '.state')" = "CLOSED" ] && echo "--closed") \
            --label "$(echo "$issue" | jq -r '.labels[].name' | tr '\n' ',' | sed 's/,$//')"
        done

        # PR'ları içe aktar
        jq -c '.[]' repo-metadata/pull_requests.json | while read pr; do
          body=$(echo "$pr" | jq -r '.body' | sed 's/\\n/\\\\n/g')
          gh pr create \
            --title "$(echo "$pr" | jq -r '.title')" \
            --body "$body" \
            --base "$(echo "$pr" | jq -r '.baseRefName')" \
            --head "$(echo "$pr" | jq -r '.headRefName')" \
            --label "$(echo "$pr" | jq -r '.labels[].name' | tr '\n' ',' | sed 's/,$//')"
        
          # PR durumunu güncelle (kapalı/merge edilmiş)
          if [ "$(echo "$pr" | jq -r '.state')" = "CLOSED" ]; then
            pr_number=$(gh pr list --json number -q ".[] | select(.title == \"$(echo "$pr" | jq -r '.title')\") | .number")
            gh pr close $pr_number
          elif [ "$(echo "$pr" | jq -r '.state')" = "MERGED" ]; then
            pr_number=$(gh pr list --json number -q ".[] | select(.title == \"$(echo "$pr" | jq -r '.title')\") | .number")
            gh pr merge $pr_number --merge
          fi
        done
      env:
        # Ortam değişkeni çakışmasını önle
        GITHUB_TOKEN: ""
          


    
