name: otp-poller
description: Polls custom .NET server until doğru OTP girilir
inputs:
  base_url:
    description: Base URL of OTP server
    required: true
  unique_key:
    required: true
outputs:
  otp:
    description: Verified OTP code
runs:
  using: "composite"
  steps:
    - name: Install jq
      shell: bash
      run: sudo apt-get update -y && sudo apt-get install -y jq

    - id: poll
      name: Wait correct OTP
      shell: bash
      env:
        WAIT_SECONDS: 120
      run: |
        BASE_URL="${{ inputs.base_url }}"
        UNIQUE_KEY="${{ inputs.unique_key }}"

        trap 'curl -s -X POST "$BASE_URL/invalidate?unique_key=$UNIQUE_KEY" >/dev/null || true' EXIT

        EXPECTED=$(curl -s "$BASE_URL/otp?unique_key=$UNIQUE_KEY" | jq -r '.otp')

        if [[ -z "$EXPECTED" || "$EXPECTED" == "null" ]]; then
          echo "::error::Sunucudan beklenen OTP alınamadı."
          exit 1
        fi

        echo "Tarayıcıda aç: $BASE_URL/?unique_key=$UNIQUE_KEY"

        DEADLINE=$(( $(date +%s) + $WAIT_SECONDS ))
        while [[ $(date +%s) -lt $DEADLINE ]]; do
          ENTERED=$(curl -s "$BASE_URL/current-otp?unique_key=$UNIQUE_KEY" | jq -r '.otp // empty')
          if [[ -n "$ENTERED" ]]; then
            if [[ "$ENTERED" == "$EXPECTED" ]]; then
              echo "✅ Doğru OTP: $ENTERED"
              echo "otp=$ENTERED" >> "$GITHUB_OUTPUT"
              exit 0
            else
              echo "::error::Yanlış OTP"
              exit 1
            fi
          fi
          sleep 5
        done

        echo "::error::OTP süresi doldu, doğrulama başarısız oldu."
        exit 1
